-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.fight_state_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL UNIQUE,
  current_round integer NOT NULL DEFAULT 1 CHECK (current_round >= 1),
  current_turn integer NOT NULL DEFAULT 1 CHECK (current_turn >= 1),
  phase text NOT NULL DEFAULT 'waiting'::text CHECK (phase = ANY (ARRAY['waiting'::text, 'countdown'::text, 'selecting'::text, 'resolving'::text, 'round_end'::text, 'match_end'::text])),
  phase_started_at timestamp with time zone NOT NULL DEFAULT now(),
  player1_health integer NOT NULL DEFAULT 100 CHECK (player1_health >= 0),
  player1_max_health integer NOT NULL DEFAULT 100 CHECK (player1_max_health > 0),
  player1_energy integer NOT NULL DEFAULT 100 CHECK (player1_energy >= 0),
  player1_max_energy integer NOT NULL DEFAULT 100 CHECK (player1_max_energy > 0),
  player1_guard_meter integer NOT NULL DEFAULT 0 CHECK (player1_guard_meter >= 0 AND player1_guard_meter <= 100),
  player1_rounds_won integer NOT NULL DEFAULT 0 CHECK (player1_rounds_won >= 0),
  player1_is_stunned boolean NOT NULL DEFAULT false,
  player1_has_submitted_move boolean NOT NULL DEFAULT false,
  player2_health integer NOT NULL DEFAULT 100 CHECK (player2_health >= 0),
  player2_max_health integer NOT NULL DEFAULT 100 CHECK (player2_max_health > 0),
  player2_energy integer NOT NULL DEFAULT 100 CHECK (player2_energy >= 0),
  player2_max_energy integer NOT NULL DEFAULT 100 CHECK (player2_max_energy > 0),
  player2_guard_meter integer NOT NULL DEFAULT 0 CHECK (player2_guard_meter >= 0 AND player2_guard_meter <= 100),
  player2_rounds_won integer NOT NULL DEFAULT 0 CHECK (player2_rounds_won >= 0),
  player2_is_stunned boolean NOT NULL DEFAULT false,
  player2_has_submitted_move boolean NOT NULL DEFAULT false,
  move_deadline_at timestamp with time zone,
  countdown_ends_at timestamp with time zone,
  last_resolved_player1_move text,
  last_resolved_player2_move text,
  last_narrative text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fight_state_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT fight_state_snapshots_match_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.matches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  room_code text UNIQUE CHECK (room_code IS NULL OR room_code ~ '^[A-Z0-9]{6}$'::text),
  player1_address text NOT NULL,
  player2_address text,
  player1_character_id text,
  player2_character_id text,
  format text NOT NULL DEFAULT 'best_of_3'::text CHECK (format = ANY (ARRAY['best_of_3'::text, 'best_of_5'::text])),
  status text NOT NULL DEFAULT 'waiting'::text CHECK (status = ANY (ARRAY['waiting'::text, 'character_select'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  winner_address text,
  player1_rounds_won integer NOT NULL DEFAULT 0,
  player2_rounds_won integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  selection_deadline_at timestamp with time zone,
  player1_disconnected_at timestamp with time zone,
  player2_disconnected_at timestamp with time zone,
  disconnect_timeout_seconds integer DEFAULT 30,
  fight_phase text DEFAULT 'waiting'::text CHECK (fight_phase IS NULL OR (fight_phase = ANY (ARRAY['waiting'::text, 'countdown'::text, 'selecting'::text, 'resolving'::text, 'round_end'::text, 'match_end'::text]))),
  fight_phase_started_at timestamp with time zone,
  power_surge_deck jsonb,
  is_bot_match boolean NOT NULL DEFAULT false,
  bot_character_id text,
  player1_ban_id text,
  player2_ban_id text,
  stake_amount_stroops text,
  stake_fee_bps integer NOT NULL DEFAULT 10,
  stake_deadline_at timestamp with time zone,
  player1_stake_tx_id text,
  player2_stake_tx_id text,
  player1_stake_confirmed_at timestamp with time zone,
  player2_stake_confirmed_at timestamp with time zone,
  stake_paid_out boolean NOT NULL DEFAULT false,
  protocol_fee_stroops text,
  onchain_session_id integer,
  onchain_tx_hash text,
  onchain_contract_id text,
  CONSTRAINT matches_pkey PRIMARY KEY (id),
  CONSTRAINT matches_player1_fkey FOREIGN KEY (player1_address) REFERENCES public.players(address),
  CONSTRAINT matches_winner_fkey FOREIGN KEY (winner_address) REFERENCES public.players(address)
);
CREATE TABLE public.matchmaking_queue (
  address text NOT NULL,
  rating integer NOT NULL DEFAULT 1000,
  joined_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'searching'::text CHECK (status = ANY (ARRAY['searching'::text, 'matched'::text])),
  matched_with text,
  CONSTRAINT matchmaking_queue_pkey PRIMARY KEY (address),
  CONSTRAINT matchmaking_queue_address_fkey FOREIGN KEY (address) REFERENCES public.players(address),
  CONSTRAINT matchmaking_queue_matched_fkey FOREIGN KEY (matched_with) REFERENCES public.players(address)
);
CREATE TABLE public.moves (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  round_id uuid NOT NULL,
  player_address text NOT NULL,
  move_type text NOT NULL CHECK (move_type = ANY (ARRAY['punch'::text, 'kick'::text, 'block'::text, 'special'::text, 'stunned'::text])),
  signature text,
  signed_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT moves_pkey PRIMARY KEY (id),
  CONSTRAINT moves_round_fkey FOREIGN KEY (round_id) REFERENCES public.rounds(id)
);
CREATE TABLE public.players (
  address text NOT NULL,
  display_name text CHECK (display_name IS NULL OR length(display_name) <= 32 AND display_name ~ '^[a-zA-Z0-9_]+$'::text),
  wins integer NOT NULL DEFAULT 0 CHECK (wins >= 0),
  losses integer NOT NULL DEFAULT 0 CHECK (losses >= 0),
  rating integer NOT NULL DEFAULT 1000 CHECK (rating >= 100 AND rating <= 3000),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT players_pkey PRIMARY KEY (address)
);
CREATE TABLE public.power_surges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL,
  round_number integer NOT NULL,
  player1_card_id text,
  player2_card_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT power_surges_pkey PRIMARY KEY (id),
  CONSTRAINT power_surges_match_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.round_private_commits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL,
  round_number integer NOT NULL CHECK (round_number >= 1),
  player_address text NOT NULL,
  commitment text NOT NULL,
  encrypted_plan text,
  proof_public_inputs jsonb,
  transcript_hash text,
  onchain_commit_tx_hash text,
  verified_at timestamp with time zone,
  resolved_at timestamp with time zone,
  resolved_round_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT round_private_commits_pkey PRIMARY KEY (id),
  CONSTRAINT round_private_commits_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT round_private_commits_resolved_round_id_fkey FOREIGN KEY (resolved_round_id) REFERENCES public.rounds(id)
);
CREATE TABLE public.rounds (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  match_id uuid NOT NULL,
  round_number integer NOT NULL CHECK (round_number > 0),
  turn_number integer DEFAULT 1 CHECK (turn_number >= 1),
  player1_move text CHECK (player1_move = ANY (ARRAY['punch'::text, 'kick'::text, 'block'::text, 'special'::text, 'stunned'::text])),
  player2_move text CHECK (player2_move = ANY (ARRAY['punch'::text, 'kick'::text, 'block'::text, 'special'::text, 'stunned'::text])),
  player1_damage_dealt integer CHECK (player1_damage_dealt IS NULL OR player1_damage_dealt >= 0),
  player2_damage_dealt integer CHECK (player2_damage_dealt IS NULL OR player2_damage_dealt >= 0),
  player1_health_after integer CHECK (player1_health_after IS NULL OR player1_health_after >= 0),
  player2_health_after integer CHECK (player2_health_after IS NULL OR player2_health_after >= 0),
  player1_energy integer DEFAULT 0,
  player2_energy integer DEFAULT 0,
  player1_guard_meter integer DEFAULT 0,
  player2_guard_meter integer DEFAULT 0,
  winner_address text,
  move_deadline_at timestamp with time zone,
  countdown_started_at timestamp with time zone,
  countdown_seconds integer DEFAULT 3,
  player1_is_stunned boolean DEFAULT false,
  player2_is_stunned boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rounds_pkey PRIMARY KEY (id),
  CONSTRAINT rounds_match_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);