#!/usr/bin/env bun

import { $ } from "bun";
import { Keypair } from "@stellar/stellar-sdk";
import { mergeEnvFile, readEnvFile } from "./utils/env";
import { ensureTlsCerts } from "./utils/tls";

const RPC_URL = "https://soroban-testnet.stellar.org";
const NETWORK = "testnet";
const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";
const XLM_TOKEN_TESTNET = "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC";
const STROOPS_PER_XLM = 10_000_000n;

function usage() {
  console.log(`
Usage: bun run scripts/fund-house-liquidity.ts [--amount-xlm <number>] [--contract-id <id>] [--env-file <path>]

Defaults:
  --amount-xlm 100
  --contract-id reads VITE_ZK_BETTING_CONTRACT_ID from .env
  --env-file .env
`);
}

async function ensureTestnetFunded(address: string): Promise<void> {
  const accountRes = await fetch(`https://horizon-testnet.stellar.org/accounts/${address}`);
  if (accountRes.ok) return;

  console.log(`💰 Funding generated wallet via friendbot: ${address}`);
  const fundRes = await fetch(`https://friendbot.stellar.org?addr=${address}`, { method: "GET" });
  if (!fundRes.ok) {
    throw new Error(`Friendbot funding failed (${fundRes.status})`);
  }

  for (let attempt = 0; attempt < 8; attempt++) {
    await new Promise((r) => setTimeout(r, 1000));
    const checkRes = await fetch(`https://horizon-testnet.stellar.org/accounts/${address}`);
    if (checkRes.ok) return;
  }

  throw new Error("Friendbot funded wallet but account not visible on Horizon yet");
}

function parseArgs() {
  const args = process.argv.slice(2);
  if (args.includes("--help") || args.includes("-h")) {
    usage();
    process.exit(0);
  }

  const amountIndex = args.indexOf("--amount-xlm");
  const contractIndex = args.indexOf("--contract-id");
  const envFileIndex = args.indexOf("--env-file");

  const amountXlm = amountIndex >= 0 ? Number(args[amountIndex + 1]) : 100;
  const contractIdFromArg = contractIndex >= 0 ? args[contractIndex + 1] : "";
  const envFilePath = envFileIndex >= 0 ? args[envFileIndex + 1] : ".env";

  if (!Number.isFinite(amountXlm) || amountXlm <= 0) {
    throw new Error("--amount-xlm must be a positive number");
  }

  return {
    amountXlm,
    contractIdFromArg,
    envFilePath,
  };
}

const { amountXlm, contractIdFromArg, envFilePath } = parseArgs();
const env = await readEnvFile(envFilePath);
const contractId = contractIdFromArg || env.VITE_ZK_BETTING_CONTRACT_ID || env.ZK_BETTING_CONTRACT_ID || "";

if (!contractId) {
  throw new Error("Missing zk-betting contract ID (set VITE_ZK_BETTING_CONTRACT_ID in .env or pass --contract-id)");
}

await ensureTlsCerts();

const liquidityWallet = Keypair.random();
const liquidityAddress = liquidityWallet.publicKey();
const liquiditySecret = liquidityWallet.secret();

await ensureTestnetFunded(liquidityAddress);

const amountStroops = BigInt(Math.round(amountXlm * Number(STROOPS_PER_XLM)));

console.log(`🏦 Depositing house liquidity`);
console.log(`   Contract: ${contractId}`);
console.log(`   Wallet:   ${liquidityAddress}`);
console.log(`   Amount:   ${amountXlm} XLM (${amountStroops} stroops)`);

await $`stellar contract invoke --id ${XLM_TOKEN_TESTNET} --source-account ${liquiditySecret} --network ${NETWORK} --rpc-url ${RPC_URL} --network-passphrase ${NETWORK_PASSPHRASE} -- transfer --from ${liquidityAddress} --to ${contractId} --amount ${amountStroops.toString()}`;

const contractBalanceOutput = await $`stellar contract invoke --id ${XLM_TOKEN_TESTNET} --source-account ${liquiditySecret} --network ${NETWORK} --rpc-url ${RPC_URL} --network-passphrase ${NETWORK_PASSPHRASE} -- balance --id ${contractId}`.text();

await mergeEnvFile(envFilePath, {
  HOUSE_LIQUIDITY_WALLET_ADDRESS: liquidityAddress,
  HOUSE_LIQUIDITY_WALLET_SECRET: liquiditySecret,
  HOUSE_LIQUIDITY_LAST_AMOUNT_XLM: String(amountXlm),
  HOUSE_LIQUIDITY_LAST_CONTRACT_ID: contractId,
}, {
  headerComment: [
    "# Auto-generated by house liquidity script",
  ],
});

console.log("✅ House liquidity deposit complete");
console.log(`📦 Contract token balance response: ${contractBalanceOutput.trim()}`);
console.log("🔐 Saved generated liquidity wallet credentials to .env (HOUSE_LIQUIDITY_*)");
